#!/bin/bash

set -euo pipefail

git submodule update --init

# Bashrc, zshrc, and inputrc
ln -f -s ~/dotfiles/bashrc ~/.bashrc
ln -f -s ~/dotfiles/zshrc ~/.zshrc
ln -f -s ~/dotfiles/inputrc ~/.inputrc

# Git
ln -f -s ~/dotfiles/gitconfig ~/.gitconfig
if [ "$(uname)" = "Darwin" ]; then
    lazygit_config_directory=~/Library/Application\ Support/jesseduffield/lazygit
else
    lazygit_config_directory=~/.config/jesseduffield/lazygit
fi
mkdir -p "$lazygit_config_directory"
ln -f -s ~/dotfiles/lazygit-config.yml "$lazygit_config_directory"/config.yml

# Tmux
ln -f -s ~/dotfiles/tmux.conf ~/.tmux.conf

mkdir -p ~/.config/nvim
ln -f -s ~/dotfiles/nvim.lua ~/.config/nvim/init.lua
ln -f -s ~/dotfiles/lazy-lock.json ~/.config/nvim/lazy-lock.json

echo Infected.
