#!/bin/bash

set -euo pipefail

git submodule update --init

# Bashrc, zshrc, and inputrc
ln -f -s ~/dotfiles/bashrc ~/.bashrc
ln -f -s ~/dotfiles/zshrc ~/.zshrc
ln -f -s ~/dotfiles/inputrc ~/.inputrc

# Git
ln -f -s ~/dotfiles/gitconfig ~/.gitconfig

# Tmux
ln -f -s ~/dotfiles/tmux.conf ~/.tmux.conf

# Vim
curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
ln -f -s ~/dotfiles/vimrc ~/.vimrc
rm -rf ~/.vim
ln -f -s ~/dotfiles/vim ~/.vim
mkdir -p ~/.config/nvim
ln -f -s ~/dotfiles/init.vim ~/.config/nvim/init.vim

echo Infected.
