#!/bin/bash

# Bashrc and inputrc
ln -f -s ~/dotfiles/bashrc ~/.bashrc
ln -f -s ~/dotfiles/inputrc ~/.inputrc

# Git
ln -f -s ~/dotfiles/gitconfig ~/.gitconfig

# Vim stuffs.
ln -f -s ~/dotfiles/vimrc ~/.vimrc
rm -rf ~/.vim
ln -f -s ~/dotfiles/vim ~/.vim

echo "Infected."
